- app/server/Dockerfile
Task:
Created Dockerfile in app/server and got the image running on Docker Desktop.
https://docs.docker.com/get-started/02_our_app/
SSH Key Problem Fixed:
Had problems with SSH key being denied. Fixed by deleting pub and private keys from .ssh folder, deleting SSH key in Github settings, then following the SSH key instructions again at https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
> Dockerized express API

- .env-template
Modified .env.template to include API_REF and API_PORT.
- [ x] Refactoring / Documentation
- [x ] No
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
> Added API_REF and API_PORT to .env.template

- app/client/Dockerfile
- app/client/nginx.conf
- docker-compose.yaml
- Creates and configures the docker-compose.yaml
- Adds a nginx.conf to the client directory
Everyone on the team pulled the changes to the branch and successfully built the server and client containers
> Brandon add docker compose

- app/server/db.js
- docker-compose.yaml
- Fixed env variables not being accessable to containers. Just had to add 2 lines in docker-compose.yaml
- Removed a string in db.js to test that the database connection could work with the URI from the .env file instead of just defaulting to the string.
Removed a string in db.js to test that the database connection could work with the URI from the .env file instead of just defaulting to the string. Verified that the database had connected in docker console.
> Fixed env variables not being accessable in containers

- app/server/README.md
- Creates a README.md within the server directory which explains which commands to use for running the server on a local machine
No tests necessary.
> Creates README.md within the server directory.

- openshift/templates/api-dc.yaml
> Non-templated API Deployment Config

- .github/workflows/build-deploy-hwp-api.yaml
> Creating Git Action for Build/Deploy API to DEV

- .github/workflows/build-deploy-hwp-api.yaml
> Replaced 'REPLACE_ME' variables in build-deploy-hwp-api.yaml

- docker-compose.yaml
> Added default MONGO_URI in docker-compose.yaml

- .github/helpers/deploy-api.sh
> Added deploy-api.sh

- openshift/templates/api-dc.yaml
> Templatize API Deployment Config

- .github/workflows/build-deploy-hwp-frontend.yaml
> Creating Git Action for Build/Deploy Frontend to DEV

- .github/workflows/build-deploy-hwp-api.yaml
> Introducing Debug Statement

- .github/helpers/deploy-api.sh
> Introducing Case into working directory

- app/client/Dockerfile
> Update Dockerfile COPY .env

- app/server/Dockerfile
> Using NPM Install to install project dependencies

- .github/helpers/application_health.sh
> Creating Application Health Helper

- .github/workflows/test-api-deploy.yaml
> Creating API TEST Deploy Git Action

- .github/workflows/test-frontend-deploy.yaml
> Creating Frontend TEST Deploy Git Action

- openshift/templates/api-dc.yaml
> Adding Mongo Connection String via Secret

- openshift/templates/api-dc.yaml
> Updating Default Value

- .github/workflows/build-deploy-hwp-api.yaml
> Updating API Application Name Secret Reference

- .github/workflows/build-deploy-hwp-frontend.yaml
> Updating Frontend Application Name Secret Reference

- openshift/templates/api-dc.yaml
> Update API Deployment Config Secret Reference

- openshift/templates/frontend-dc.yaml
> Updating Frontend Deployment Config Env Vars

- openshift/templates/api-dc.yaml
- openshift/templates/api-service.yaml
- openshift/templates/frontend-dc.yaml
- openshift/templates/frontend-service.yaml
> Adding Services + Making Changes to Deploy Configs

- docker-compose.yaml
> Adding API port to environment

- .github/helpers/deploy.sh
- .github/workflows/build-deploy-hwp-api.yaml
- .github/workflows/build-deploy-hwp-frontend.yaml
- openshift/templates/frontend-dc.yaml
> Updating Deploy Script

- openshift/templates/frontend-dc.yaml
> Updating Image Location

- app/client/Dockerfile
> Change group and change mod nginx in react Dockerfile

- app/client/src/routes.js
> added /hwp/ to all routes in client/src/routes.js

- .github/workflows/build-deploy-hwp-api.yaml
- .github/workflows/build-deploy-hwp-frontend.yaml
- .github/workflows/test-api-deploy.yaml
- .github/workflows/test-frontend-deploy.yaml
> Creating More Jobs in Git Actions

- .env-template
- README.md
- app/client/src/components/editProfile.js
- app/client/src/components/joinButton.js
- app/client/src/components/modals/addPost.js
- app/client/src/components/profileInfo.js
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/redux/ducks/postDuck.js
- app/client/src/views/login.js
- app/client/src/views/register.js
- app/server/db.js
Updated .env, .env-template, app/server/db.js, and references to api in app/client fetch calls
- Changes to .env variables
- Changes to .env-template
- Updated mongo uri in app/server/db.js
- Updated references to api in app/client fetch calls
- Updated README
Tested lookup of db collections in mongo CLI and tested register/login/view communities list in browser.
> HWP-256: Updated env variables

- openshift/templates/frontend-dc.yaml
> Adding Pod Port to Deployment Config

- openshift/templates/frontend-service.yaml
> Changing Port on Service Template

- openshift/templates/mongo-network-policy.yaml
> Creating Mongo Network Policy Template

- app/client/src/redux/ducks/authDuck.js
- app/client/src/redux/index.js
- app/client/src/views/login.js
- app/client/src/views/register.js
- Added authDuck.js
- Modified client/login.js to use the authDuck redux action as opposed to inside-component call
- Modified client/register.js to use the authDuck redux action as opposed to inside-component call
- Modified redux store to include authReducer
> Added authDuck.js

- .github/PULL_REQUEST_TEMPLATE.md
- Added requires section to github pr template to specify if changes need to be made to untracked files.
> Added requires to pr template

- app/client/src/index.js
Checking if window._env_.API_REF exists, if not, then assign window._env_ to process.env
**REQUIRES**:
> Added a check for window._env_

- app/client/src/index.js
Added require('dotenv') to index.js
**REQUIRES**:
> Added require('dotenv')

- app/client/src/index.js
- package-lock.json
- package.json
> Installing dotenv

- app/client/src/index.js
> commented out require dotenv and renaming process.env to window._env_ in index.js

- app/client/package.json
Pins the version of react-error-overlay to fix issue with react-scripts.
- Adds "react-error-overlay": "6.0.9" to package.json
**REQUIRES**:
> Fixes undefined process in react

- app/client/package-lock.json
- app/client/src/index.js
Runs npm i in the client directory
**REQUIRES**:
> Update package.json and package-lock.json to use react-error-overlay

- app/client/src/index.js
- app/client/src/redux/ducks/authDuck.js
> Changed process.env in authDuck

- app/client/env.sh
> Change to env.sh

- .env-template
- app/client/Dockerfile
- app/client/README.md
- app/client/env.sh
- app/client/src/components/editProfile.js
- app/client/src/components/joinButton.js
- app/client/src/components/modals/addPost.js
- app/client/src/components/profileInfo.js
- app/client/src/redux/ducks/authDuck.js
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/redux/ducks/postDuck.js
**REQUIRES**:
See .env-template for changes.
- Changed ternary operator to correctly work with local development (changes explained below).
- Removed unnecessary part of path in app/client/Dockerfile for COPY on env.sh
- Updated client/app/README to explain how env variables are loaded in react app
- Added REACT_APP_LOCAL_DEV=true environment variable to assist with ternary operator
- Updated env.sh to only copy variables prefixed with REACT_APP_ into the frontend container.
Explanation of ternary operator:
If …
> Cleanup Changes to React Env Variables

- app/client/src/redux/ducks/authDuck.js
Simple 1 line test to see if process.env works in react on OpenShift.
Will revert if doesn't work.
> Testing process.env for openshift frontend

- .github/helpers/deploy-api.sh
- .github/helpers/deploy.sh
- .github/workflows/build-deploy-hwp-frontend.yaml
- .github/workflows/prod-frontend-deploy.yaml
- .github/workflows/test-frontend-deploy.yaml
- openshift/templates/frontend-dc.yaml
I've created DEV_API_REFERENCE, TEST_API_REFERENCE, PROD_API_REFERENCE github secrets to store the API URL generated from the route in openshift that points the service/deployment config for the HWP Express API. These URLS are passed as parameters in the deployment config for the React Frontend, and passed appropriately through each github action for deploying to dev/test/prod.
HWP-262
For pull requests that are not just a simple fix, please check …
> HWP-262 Parameterizing API Reference in Deployment Config

- .env-template
- app/client/src/redux/ducks/authDuck.js
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/redux/ducks/postDuck.js
- Changes to the apiRef const in each duck
- Added REACT_APP_ before the LOCAL_DEV env variable
> Changed logic for checking LOCAL_DEV

- .env-template
> Removed value true from env-template/REACT_APP_LOCAL_DEV

- app/server/README.md
- app/server/express.js
- app/server/models/community.model.js
- app/server/models/post.model.js
- app/server/models/user.model.js
- app/server/package-lock.json
- app/server/package.json
- app/server/routes/v1/community.js
- app/server/routes/v1/healthCheck.js
- app/server/routes/v1/login.js
- app/server/routes/v1/logout.js
- app/server/routes/v1/post.js
- app/server/routes/v1/profile.js
- app/server/routes/v1/register.js
- app/server/routes/v1/token.js
- docker-compose.yaml
Test swagger in [browser](http://localhost:5000/api-docs) on local machine.
- Added swagger docs to document the API
- Swagger docs includes authentication methods for testing
- Fixed patch operations
- Removed need for auth to access health enpoint
- Added to app/server/README
**Not required but recommended to change env variable JWT_TOKEN_EXPIRY=5m**
This is to allow you more time for testing before your authentication expires.
Tested all endpoints in swagger docs.
For pull requests that are not just a …
> HWP-192: Added swagger + testing capability in swagger

- app/client/src/views/login.js
- Changed client/views/login.js to redirect to /home on successful login
> Redirecting from '/' to '/home' on successful login

- app/server/README.md
- app/server/express.js
- app/server/models/post.model.js
- app/server/models/user.model.js
- app/server/routes/v1/community.js
- app/server/routes/v1/post.js
- app/server/routes/v1/register.js
- app/server/routes/v1/user.js
- Added /api/user DELETE operation
- Fixed overlooked /api/post GET to only show posts in communities user is apart of
- Removed ability to set API version in req header. I think this was unnecessary and the functionality wasn't the best. It is now required to use the env variable API_VERSION to set the API version.
- Renamed profile endpoint to user. This makes more sense as operations to the user collection do not always involve the profile. This also makes more sense moving forward as we implement admin and moderator features.
@mattsiel @dbarkowsky Please note the changes to the API.
@ZachBourque Please note the change from profile -> user for changes in the frontend.
If there are any …
> HWP-302: Added ability to remove user

- .github/helpers/deploy-api.sh
- .github/workflows/prod-api-deploy.yaml
- .github/workflows/test-api-deploy.yaml
> Refactoring Github Actions for API Build, Tag, Push, Deploy

- .github/workflows/build-deploy-hwp-api.yaml
> Missing Github Action Update

- app/client/src/components/modals/addPost.js
- Calling the onClose function in addPost modal on successful post creation
- Converted html text input to MUI Text input to allow for value binding
> HWP-264: Close post modal

- app/server/tests/api-getCommunity.test.js
- app/server/tests/get_community.test.js
- app/server/tests/jest.config.js
- creates a jest configuration file for test files to run
- creates tests to get communities from the api endpoint
- tests different scenarios, such as whether the user is logged in or not.
> HWP-271 Create test file for GET /api/community

- app/server/express.js
- app/server/models/community.model.js
- app/server/routes/v1/community.js
- app/server/routes/v1/logout.js
- app/server/routes/v1/token.js
- Server-side parts of HWP-301: Added community rules endpoints
- Updated community PATCH and DELETE operations to check for creator of community
- Added try catch to login route
- Added missing responses to login route
- Removed cookieAuth from swagger as it wasn't actually doing anything. Refresh tokens are stored in cookies.
Recommended you remove the .mongo/data files. If not, communities you have already created will not work as expected.
@mattsiel @dbarkowsky Updated the login route so it shouldn't respond with any 500 errors.
@ZachBourque Communities now store user.name in the creator …
> Added community rules, login route changes, updates to community routes

- app/server/models/post.model.js
- app/server/routes/v1/post.js
- Updated post model to include 'pinned' as well as changing required fields.
- Added /api/post/community/{title} GET to return posts from a specified community.
- Editing a post no longer allows for changing of the post creator.
- Creating and editing a post only allows for 3 pinned posts per community (NOTE: In the future only moderators of a community will be allowed to pin posts).
- Pinned posts show at the top of the returned posts list data. …
> HWP-295: Added post pinning

- openshift/templates/frontend-dc.yaml
> Updating Frontend Environment Variables

- openshift/templates/api-dc.yaml
> HWP-328 Updating Environment Variable Values

- app/server/tests/api-deleteCommunity.test.js
- app/server/tests/api-getCommunity.test.js
-Ticket number 273
- creates a test suite to test the delete community requests
- changed the descriptions of the get Communities tests
> Hwp 273 - Create test file for DELETE /api/community/{title}

- app/server/models/community.model.js
- app/server/models/post.model.js
- app/server/routes/v1/community.js
- app/server/routes/v1/post.js
- Community creator (eventually moderators as well) can set tags for the community. Ex: Informative
- Community creator can remove tags from the community. This also removes all tag references on posts within the community.
- User can view community tags (that were set by community creator) as well as a count for how many times that tag was used on posts within the community.
- User can tag a post (limit 1 tag per user per post, only allows tags that were set within the community).
- User can untag a post.
- Added optional query parameter to /api/post/community/{title} to return all posts within community tagged by 'tag'. 
If there are any requirements for the developer to make after this PR …
> HWP-318: Post/Community tagging api

- app/server/tests/functions/postFunctions.js
- Jira Ticket HWP-331
- creates a file for testing API post requests
- includes all API requests that are commented on swagger
> HWP-331 Create a file for testing API post requests

- .eslintrc.json
- app/server/express.js
- app/server/swagger-conf.js
- Max-lines 500
- Moved swagger configuration from express.js to its own file
> Added max-lines to ESLint, created swagger-conf.js

- app/server/routes/v1/user.js
> Added .send in user patch and delete res

- app/server/middleware/authenticateToken.js
> authenticateToken.js was missing return

- app/client/src/components/communitiesList.js
- app/client/src/components/createCommunity.js
- app/client/src/components/joinButton.js
- app/client/src/components/joinCommunitiesList.js
- app/client/src/components/usersCommunitiesList.js
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/views/home.js
- app/client/src/views/profilePage.js
- Added joining/leaving redux actions in communityDuck
- Changed the communities list to list all communities
- Added joining/leaving functionality in frontend
- Create community 
> HWP-291 Add Joining/Leaving community functionality in frontend

- app/client/src/components/usersCommunitiesList.js
- Removed duplicate code in usersCommunitiesList.js that is present in joinButton.js
> Removing duplicate code from usersCommunitiesList.js

- app/client/src/privateComponent.js
- app/client/src/routes.js
- Added privateComponent.js which conditionally redirects to /login if the user is not logged in
- Calls createError redux action which alerts the user of the redirect and the reason for it
- Modifed routes.js to implement the PrivateComponent component
> HWP-309 Handle Unauthorized Access to Pages

- app/server/package.json
- app/server/tests/api-deleteUser.test.js
- app/server/tests/api-getUser.test.js
- app/server/tests/api-patchUser.test.js
- app/server/tests/api-register.test.js
- app/server/tests/functions/userFunctions.js
Added test files for patch, delete, and get user.
Adjusted working in register test.
Scrambled my initial branch so bad, remade it like this with simpler commits.
> Hwp 330 create files for user tests

- app/client/src/App.js
- app/client/src/components/alertList.js
- app/client/src/components/modals/flagPostModal.js
- app/client/src/components/post.js
- app/client/src/components/postsList.js
- app/client/src/layout/footer.js
- app/client/src/redux/ducks/flagDuck.js
- app/client/src/redux/index.js
- Created files
- post.js
- Created to standardize the display of a post and comply with the D.R.Y. principle
- flagPostModal.js
- Modal which allows the user to flag a post and select the reason for flagging via a dropdown
- flagDuck.js
- Contains functionality for opening the flag post modal, and flagging said post
- alertList.js
- Lists all alerts in alertDuck.js and displays them in the top right of the screen
- Removed unneeded comments from App.js
- 
Please describe the tests that you ran to verify your …
> HWP-351 Add frontend post flagging functionality

- app/client/src/components/editProfile.js
- app/client/src/components/modals/addPostModal.js
- app/client/src/components/profileInfo.js
- app/client/src/redux/ducks/authDuck.js
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/redux/ducks/flagDuck.js
- app/client/src/redux/ducks/profileDuck.js
- app/client/src/views/login.js
- app/client/src/views/register.js
@BradyMitch 
- Renamed first_name to firstName, last_name to lastName, and name to username, in order to comply with backend changes 
- FIxed a breaking change in flagDuck which would cause the website to display a white screen
> Matching frontend variable names with backend

- app/server/middleware/generateRefreshToken.js
- app/server/middleware/generateToken.js
- app/server/models/comment.model.js
- app/server/models/community.model.js
- app/server/models/post.model.js
- app/server/models/user.model.js
- app/server/package-lock.json
- app/server/package.json
- app/server/routes/v1/comment/comment.js
- app/server/routes/v1/community/community.js
- app/server/routes/v1/community/communityFlags.js
- app/server/routes/v1/community/communityMembers.js
- app/server/routes/v1/community/communityRules.js
- app/server/routes/v1/community/communityTags.js
- app/server/routes/v1/login.js
- app/server/routes/v1/logout.js
- app/server/routes/v1/post/post.js
- app/server/routes/v1/post/postFlags.js
- app/server/routes/v1/post/postTags.js
- app/server/routes/v1/register.js
- app/server/routes/v1/token.js
- app/server/routes/v1/user.js
- Added moment to app/server packages: [https://momentjs.com/](https://momentjs.com/)
- Comment edits are saved along with a timestamp
- Creation of communities, posts, and comments includes a time stamp
@ZachBourque @dbarkowsky 
- Changed references of user.name to user.username
- Changed references of first_name and last_name to firstName and LastName
- Changed references of refresh_token to refreshToken
These changes are to keep all database fields within a set naming convention (camelCase), and the change of username was to prevent confusion.
Remove files from ./mongo/data to remove …
> HWP-300: Comment edit history and timestamps

- app/server/routes/v1/post/post.js
- Post delete endpoint now deletes post and comments on post
Tested in swagger
> HWP-358: Fixed delete post not actually deleting

- app/client/src/layout/header.js
- app/client/src/privateComponent.js
- app/client/src/routes.js
- app/client/src/views/404Page.js
- Modified header.js to only render the sidebar if the user is logged in
- Added 404Page.js
- Removed undefined value from privateComponent.js
> Only show sidebar if logged in

- app/server/express.js
- app/server/models/comment.model.js
- app/server/routes/v1/comment/comment.js
- app/server/routes/v1/comment/commentReply.js
- app/server/routes/v1/community/community.js
- app/server/routes/v1/user.js
- app/server/swagger-conf.js
- Added schema fields for comment: replyTo (id of comment that the comment is a reply to) and community (title of community the comment belongs to).
- Added endpoints to create a reply to a comment, and list all replies to a comment.
- Removing a community also removes all comments in the community.
Tested removing a community with posts and comments.
Tested comment reply endpoints.
If Yes: Has Docker …
> HWP-316: Comment replys api

- app/server/models/post.model.js
- app/server/routes/v1/community/communityTags.js
- app/server/routes/v1/post/post.js
This is to help with frontend functionality, so fetch calls dont need to be made to see what tags are available in the community.
- Added availableTags to post schema (array of tag names in the community).
- Community tag and untag now also push or pull to this array of tags.
Tested in swagger - Setting and unsetting community tags, then seeing if they appear in the return on "get posts by community title".
For pull requests that are not just a simple fix, please check that the branch works on your local …
> HWP-362: Added availableTags to post schema

- app/client/src/components/modals/deletePostModal.js
- app/client/src/components/modals/flagPostModal.js
- app/client/src/components/post.js
- app/client/src/components/postsList.js
- app/client/src/redux/ducks/modalDuck.js
- app/client/src/redux/ducks/postDuck.js
- app/client/src/redux/index.js
- Added post deletion functionality
- Created modalDuck.js to handle the state of modals that posts use
- Deleted flagDuck.js
- Moved flagPost from flagDuck to postDuck
> HWP-287 Post Deletion

- app/server/routes/v1/post/post.js
- Creating a post includes availableTags from community
> Post creation includes availabaleTags

- app/server/express.js
- app/server/models/comment.model.js
- app/server/routes/v1/comment/comment.js
- app/server/routes/v1/comment/commentReply.js
- app/server/routes/v1/comment/commentVoting.js
- app/server/swagger-conf.js
- Comment upvote/downvote 
- Upvoting when you have already upvoted will clear the vote, same for downvote
- Upvoting when you have already downvote will change your vote, and vice versa
- added hasreplies to comment to show if it has replies
- "Get comments from post id" now doesn't show reply comments
- Comments are ordered by upvote/downvotes or in chronological order
Best to remove ./mongo/data as existing comments will not work as expected.
Tested voting and comment ordering in swagger.
For pull requests …
> HWP-312: Comment voting

- app/server/routes/v1/comment/commentVoting.js
- app/server/routes/v1/post/post.js
- Following the changes to the user schema's communities array, I forgot to update the code in /api/post GET and /api/comment/vote PATCH. The issue was with accessing the user's list of communities.
Swagger GET post
> Fixed GET /api/post checking for communities user is a part of

- app/server/middleware/generateToken.js
- app/server/routes/v1/community/community.js
- app/server/routes/v1/community/communityMembers.js
- Added user id to jwt encoding
- Fixes for accessing user's communities list because of changes made for user engagement in communities
Tested swagger Delete community, Join and leave community
> Fixes getting user's communities.community

- app/server/routes/v1/community/community.js
- Modified community.js to allow for tags upon community creation
> Modified community.js to allow for tags upon community creation

- openshift/templates/api-dc.yaml
> Updating API Environment Variables

- app/server/tests/api-deletePostTags.test.js
- app/server/tests/api-getPostTags.test.js
- app/server/tests/api-postPostTags.test.js
- app/server/tests/functions/communityFunctions.js
- app/server/tests/functions/postFunctions.js
- Wrote preliminary tests for Post Tags. 
- Cleaned up function files a bit. (spacing & .query use)
Tested locally.
> HWP-365 Added post tag tests. Cleaned up functions.

- app/server/express.js
- app/server/middleware/authenticateToken.js
- app/server/middleware/sanitizeInputs.js
- app/server/package-lock.json
- app/server/package.json
- app/server/responseError.js
- app/server/routes/v1/comment/comment.js
- app/server/routes/v1/comment/commentReply.js
- app/server/routes/v1/comment/commentVoting.js
- app/server/routes/v1/community/community.js
- app/server/routes/v1/community/communityFlags.js
- app/server/routes/v1/community/communityMembers.js
- app/server/routes/v1/community/communityRules.js
- app/server/routes/v1/community/communityTags.js
- app/server/routes/v1/login.js
- app/server/routes/v1/logout.js
- app/server/routes/v1/post/post.js
- app/server/routes/v1/post/postFlags.js
- app/server/routes/v1/post/postTags.js
- app/server/routes/v1/register.js
- app/server/routes/v1/token.js
- app/server/routes/v1/user.js
[Click here to open the Swagger Dev Environment.](https://hwp-express-api-d63404-dev.apps.silver.devops.gov.bc.ca/api-docs/)
- Added ResponseError class to capture errors in api responses.
- Updated all routes to use this custom Error class when there is an error.
- Changed PATCH api/post/:id so the user can't change the community of a post.
Tested a few endpoints with invalid input to get an error response.
For pull requests that are not just a simple fix, please check that the branch works on your local …
> HWP-361: API response error handling

- app/client/package-lock.json
- app/client/package.json
- app/client/src/App.jsx
- app/client/src/Routes.jsx
- app/client/src/components/ProfileInfo.jsx
- app/client/src/layout/Footer.jsx
- app/client/src/layout/Header.jsx
- app/client/src/layout/SideMenu.jsx
- app/client/src/layout/footer.css
- app/client/src/layout/header.css
- app/client/src/layout/sideMenu.css
- app/client/src/redux/ducks/authDuck.js
- app/client/src/redux/ducks/profileDuck.js
- app/client/src/views/ProfilePage.jsx
- Updates profile page
- Updates the header bar
- Updates the footer bar
- Adds a fix for frontend hot reloading
> Hwp 349 - Build Functional Profile Page

- app/client/src/components/CommunitiesList.jsx
- app/client/src/components/Community.jsx
- app/client/src/components/modals/DeleteCommunityModal.jsx
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/redux/ducks/modalDuck.js
This PR adds in functionality for the creator of a community to delete their community
- Creation of Community.jsx
- deleteCommunity redux action
> HWP-286 Creator of community can delete community

- app/client/src/views/ProfilePage.jsx
- Material UI 'chips' added to the user profile page
Ran the backend containers and frontend dev server. The app loaded and the new 'interests' section on the profile page was present.
> HWP-349 - Build Functional Profile Page

- app/server/tests/api-deleteCommunity.test.js
- app/server/tests/api-deletePost.test.js
- app/server/tests/api-deletePostFlags.test.js
- app/server/tests/api-deletePostTags.test.js
- app/server/tests/api-getCommunitiesByTitle.test.js
- app/server/tests/api-getCommunity.test.js
- app/server/tests/api-getCommunityRules.test.js
- app/server/tests/api-getPost.test.js
- app/server/tests/api-getPostFlags.test.js
- app/server/tests/api-getPostTags.test.js
- app/server/tests/api-patchPost.test.js
- app/server/tests/api-postPost.test.js
- app/server/tests/api-postPostFlags.test.js
- app/server/tests/api-postPostTags.test.js
- app/server/tests/api-setCommunityRules.test.js
- app/server/tests/functions/communityFunctions.js
- added test files for community rules
- cleaned up code in other community files
- changed community functions to be more readable
> Hwp 370 - Create API tests for Community Rules

- app/server/routes/v1/login.js
- app/server/routes/v1/logout.js
- Login endpoint wasn't saving refresh token to the database because of a typo.
> HWP-390: Fix for refresh token saving to database

- app/client/src/axiosInstance.js
- app/client/src/components/PrivateComponent.jsx
- app/client/src/redux/ducks/authDuck.js
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/redux/ducks/postDuck.js
- app/client/src/redux/ducks/profileDuck.js
- app/client/src/store.js
- app/client/src/views/HomePage.jsx
- Custom axios instance which will regenerate a new access token from the API if the current one is expired
- Added support for refreshing the page, and persistent login
> Zach axios instance

- app/server/functions/checkPatchQuery.js
- app/server/functions/checkUserIsMemberOfCommunity.js
- app/server/functions/findSingleDocuments.js
- app/server/functions/updateCommunityEngagement.js
- app/server/middleware/sanitizeInputs.js
- app/server/routes/v1/comment/comment.js
- app/server/routes/v1/comment/commentReply.js
- app/server/routes/v1/comment/commentVoting.js
- app/server/routes/v1/community/community.js
- app/server/routes/v1/community/communityFlags.js
- app/server/routes/v1/community/communityMembers.js
- app/server/routes/v1/community/communityRules.js
- app/server/routes/v1/community/communityTags.js
- app/server/routes/v1/post/post.js
- app/server/routes/v1/post/postFlags.js
- app/server/routes/v1/post/postTags.js
- app/server/routes/v1/user.js
[Click here to open the Swagger Dev Environment.](https://hwp-express-api-d63404-dev.apps.silver.devops.gov.bc.ca/api-docs/)
There are changes to many files, but that is just because each of these 4 functions had to be refactored into the existing routes. When reviewing the code, focus on the files in the `functions/` directory.
- Added and implemented `checkPatchQuery()`, which when given a request body, document, and blacklisted fields, will return a query or a version of the request body that has all of the blacklisted fields removed. This query that it returns is used to edit documents and so it's important that we don't allow users to edit say the post that a comment is on.  
- Added and implemented `findSingleDocuments()`, which …
> HWP-346: Reusable api functions

- app/client/src/Routes.jsx
- app/client/src/components/Comment.jsx
- app/client/src/components/CommentsList.jsx
- app/client/src/components/CreateComment.jsx
- app/client/src/components/SingularPost.jsx
- app/client/src/redux/ducks/postDuck.js
This PR allows for creation of comments on posts, as well as navigating to a post page, denoted by URL/post/:id.
- Creation of singularPost.jsx to easily allow for displaying a single post
- createComment redux action
- getComments redux action
- Comment, CommentsList, and CreateComment components
> HWP-317 Frontend Post Commenting Functionality

- app/client/src/components/Post.jsx
- app/client/src/components/PostsList.jsx
- app/client/src/components/modals/EditPostModal.jsx
- app/client/src/redux/ducks/modalDuck.js
- app/client/src/redux/ducks/postDuck.js
This PR allows for post editing in the front end, by use of a modal
- Creation of EditPostModal.jsx
- Addition of editPost in modalDuck state
> HWP-285 Frontend Post Editing Functionality

- openshift/templates/api-dc.yaml
> HWP-393 Adding Logging Variable

- .env-template
- app/server/express.js
- app/server/functions/logger.README.md
- app/server/functions/logger.js
- app/server/middleware/initLogger.js
- app/server/package-lock.json
- app/server/package.json
- app/server/routes/v1/comment/comment.js
- app/server/routes/v1/comment/commentReply.js
- app/server/routes/v1/comment/commentVoting.js
- app/server/routes/v1/community/community.js
- app/server/routes/v1/community/communityFlags.js
- app/server/routes/v1/community/communityMembers.js
- app/server/routes/v1/community/communityRules.js
- app/server/routes/v1/community/communityTags.js
- app/server/routes/v1/login.js
- app/server/routes/v1/logout.js
- app/server/routes/v1/post/post.js
- app/server/routes/v1/post/postFlags.js
- app/server/routes/v1/post/postTags.js
- app/server/routes/v1/register.js
- app/server/routes/v1/token.js
- app/server/routes/v1/user.js
- docker-compose.yaml
- Logs api requests to console.
- logger.js in /app/server/functions handles the logging functions.
- logger.README.md in app/server/functions explains how to use the logger.
- initLogger.js middleware in /app/server/middleware initializes the logger for each request.
- Masks specified fields in request bodies. `{ "password": "***" }`
- Automatically switches between PDT and PST.
Example logs:  
[Successful Login](https://i.imgur.com/B3igPUi.png)  
[Successful Get Communities](https://i.imgur.com/YQNwT3m.png)  
[ResponseError Create Community](https://i.imgur.com/HXzr7Cj.png)  
[Error Create Community](https://i.imgur.com/37pLNL1.png)  
Adds package: [ansi-colors](https://www.npmjs.com/package/ansi-colors)
Add 'Requires Attention' label …
> HWP-373: API Request Logger

- app/server/middleware/initLogger.js
- Logger copies req.body instead of taking by reference
> HWP-397: Fix logger setting req.body instead of copying

- app/server/models/comment.model.js
- app/server/routes/v1/comment/comment.js
- app/server/routes/v1/user.js
- Creator's name is now shown on comments.
Edited the firstName and lastName of an account and saw the name was visible on comments.
> HWP-394: Creator name visible on comments

- app/client/src/axiosInstance.js
- app/client/src/components/Tag.jsx
- app/client/src/components/TagsList.jsx
This PR adds badges in the top right corner of tags which displays the number of tags a given tag has.
- Added Badge to Tag.jsx
> HWP-396 Post Tag Badges

- app/client/src/App.jsx
- app/client/src/components/ProfileInfo.jsx
- app/client/src/layout/Header.jsx
- app/client/src/views/ProfilePage.jsx
- Change the previous header bar implementation into an MUI AppBar component
- Change the previous side menu implementation into an MUI Drawer component containing an MUI List
Ran the application using docker-compose and used the menu to navigate the application.
> HWP-280: Fix Persistant Side Menu

- app/client/src/Routes.jsx
- app/client/src/components/Community.jsx
- app/client/src/components/UsersCommunitiesList.jsx
- app/client/src/components/modals/AddPostModal.jsx
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/views/CommunityPage.jsx
- Added community page.  
example: [https://hwp-react-d63404-dev.apps.silver.devops.gov.bc.ca/community/Welcome](https://hwp-react-d63404-dev.apps.silver.devops.gov.bc.ca/community/Welcome)  
- Community in community list now links to the community page.
- Creating a post in the community page doesn't require you to specify the community.
Tested clicking on communities in the communities list on both homepage and communities page.
For pull requests that are not just a simple fix, please check that the branch …
> HWP-395: Community page

- app/server/routes/v1/community/community.js
- On create community, the community wasn't added to the user's community list. I must have accidently removed it when I was creating reusable functions.
Created a community and added a post.
> HWP-400: Fixed community not being added to user document

- app/server/models/user.model.js
- Added organization and interests fields to the user schema so they can be utilized by the profile page.
> HWP-363-and-381: Organization and interests added to user schema

- app/server/models/user.model.js
- app/server/routes/v1/post/post.js
- app/server/routes/v1/register.js
- app/server/routes/v1/user.js
[Click here to open the Swagger Dev Environment.](https://hwp-express-api-d63404-dev.apps.silver.devops.gov.bc.ca/api-docs/)
- Added postCount to user schema (number of posts user has created).
- Updates when creating/removing a post.
- Added postCount and registeredOn to GET /api/user
Tested alongside the frontend changes for post count, as well as on swagger (creating and deleting posts).
If Yes: Has …
> HWP-377: Backend user post count

- app/client/src/components/ProfileInfo.jsx
- User's post count shows in profile, as well as when they registered
Tested alongside backend changes to postCount. Post count displays in profile.
> HWP-377: Frontend user post count

- app/server/models/post.model.js
- app/server/routes/v1/comment/comment.js
- app/server/routes/v1/post/post.js
- app/server/routes/v1/user.js
- Added commentCount and creatorName to post schema
- commentCount updates on comment creation/deletion
- creatorName added on post creation or updated when user updates firstName or lastName
Tested with swagger, creating comments to increase commentCount on post, and editing user firstName/lastName to update post creatorName.
> HWP-401: Backend - Added commentCount and creatorName to post

- app/client/src/components/Post.jsx
- app/client/src/components/SingularPost.jsx
- Shows community, creator name, and comment count on posts in post feed.
- Shows community and creator name on post in post view.
- Clicking on community in post will redirect to the community page.
Viewed posts in homepage and on post view.
> HWP-401: Frontend - Show community, creator name, and comment count on posts

- app/client/package-lock.json
- app/client/package.json
- app/client/src/components/Post.jsx
- app/client/src/components/SingularPost.jsx
- app/client/src/components/UsersCommunitiesList.jsx
- app/client/src/views/CommunityPage.jsx
- app/client/src/views/HomePage.jsx
- Styled posts and post pages to align closely with the new wireframes
- Added published label on posts to display when the post was created
- Published label is converted from utc to the user's local time
Tested on homepage and community page.
> HWP-409: Post and post page styling

- app/client/src/components/modals/EditCommunityModal.jsx
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/redux/ducks/modalDuck.js
- app/client/src/views/CommunityPage.jsx
This PR allows the creator of a community to modify the title, description, and rules of said community
- Creation of EditCommunityModal.jsx
- Added settings button to CommunityPage.jsx
- Added editCommunity redux action
> Added modify community functionality

- app/client/package-lock.json
- app/client/package.json
- app/client/src/components/Comment.jsx
- app/client/src/components/Post.jsx
- app/client/src/components/SingularPost.jsx
- app/client/src/components/UsersCommunitiesList.jsx
- app/client/src/views/CommunityPage.jsx
- app/client/src/views/HomePage.jsx
- Added createdOn (when the comment was created).
- Added "Edited" label to comments that have been edited.
- Added voting buttons (they do NOT work. They are just in place for future implementation).
Edited a comment in swagger and viewed in the frontend.
> HWP-402: Enhancements to comments

- app/client/src/Routes.jsx
- app/client/src/views/LogoutPage.jsx
- Addition of logout page, which calls the /logout API endpoint, and clears all data in the client's memory
> HWP-411 - Logout page

- app/client/src/components/Community.jsx
- app/client/src/components/Post.jsx
- app/client/src/components/UsersCommunitiesList.jsx
- app/client/src/views/HomePage.jsx
This PR adds intuitive UI features
- When hovering the cursor over a post, the post changes border color to one that is slightly darker
- When hovering over a community name in a post, the community name turns underlined to show the user they can click
- Changed cursor to a pointer when able to click on an element
If Yes: Has Docker been …
> HWP-410 Text that redirects uses cursor pointer

- app/client/package-lock.json
- app/client/package.json
- app/client/src/Routes.jsx
- app/client/src/components/AlertList.jsx
- app/client/src/components/Comment.jsx
- app/client/src/components/CommentsList.jsx
- app/client/src/components/CommunitiesList.jsx
- app/client/src/components/Community.jsx
- app/client/src/components/CreateCommunity.jsx
- app/client/src/components/Post.jsx
- app/client/src/components/PostsList.jsx
- app/client/src/components/ProfileInfo.jsx
- app/client/src/components/UsersCommunitiesList.jsx
- app/client/src/components/modals/AddCommunityModal.jsx
- app/client/src/components/modals/DeleteCommentModal.jsx
- app/client/src/components/modals/DeleteCommunityModal.jsx
- app/client/src/components/modals/DeletePostModal.jsx
- app/client/src/components/modals/EditCommunityModal.jsx
- app/client/src/components/modals/EditPostModal.jsx
- app/client/src/components/modals/FlagPostModal.jsx
- app/client/src/layout/Footer.jsx
- app/client/src/views/HomePage.jsx
- app/client/src/views/ProfilePage.jsx
- Removes the errors and warnings in the frontend console. Said errors were being created by missing key prop, incorrect PropType, invalid MUI prop input, etc.
> HWP-412 Eliminate frontend errors/warnings

- app/server/express.js
- app/server/models/community.model.js
- app/server/routes/v1/comment/comment.js
- app/server/routes/v1/community/community.js
- app/server/routes/v1/community/communityMembers.js
- app/server/routes/v1/community/communityRules.js
- app/server/routes/v1/community/communityTags.js
- app/server/routes/v1/post/post.js
- app/server/routes/v1/register.js
- app/server/routes/v1/user.js
- Adds creatorName (Full name of community creator), memberCount, and latestActivity (date and time of latest post or comment) to community schema.
- memberCount updates when a user leaves/joins a community.
- creatorName is either user's firstName and lastName OR just firstName OR username.  
- Changed rate limit from 100 requests per minute -> 100 reqs per 15 seconds.
- Changed `creator` field to use `id` instead of `username` (the way it should have been originally).
Remove data from `mongo/data` directory. …
> HWP-404: Backend - creatorName, memberCount, and latestActivity to community

- app/client/src/components/Community.jsx
- app/client/src/components/JoinButton.jsx
- app/client/src/components/SingularPost.jsx
- app/client/src/components/UsersCommunitiesList.jsx
- app/client/src/views/CommunitiesPage.jsx
- app/client/src/views/CommunityPage.jsx
- app/client/src/views/ProfilePage.jsx
- mongo/init/data/communities.json
- Updated styles of communities page.
- Added latestActivity to communities in profile page.
- Added member count to communities.
- Changes to how join/leave community buttons show.
- Changed singular post to show local time.
- Changed ./mongo/init communities.json for Welcome community to add createdOn field.
If you didn't see in the other PR for HWP-404. You need to remove the files inside `./mongo/data` directory. If you don't there will be some unexpected behavior. 
Tested alongside HWP-404 backend …
> HWP-404: Frontend - Community Enhancements

- app/client/src/layout/Header.jsx
- User avatar in header bar links to profile page
- Ran the application and clicked on the user avatar in the header bar
> Avatar profile link

- app/client/src/components/CommunitiesList.jsx
- app/client/src/views/CommunitiesPage.jsx
- app/client/src/views/CommunityPage.jsx
- app/client/src/views/HomePage.jsx
A number of elements needed minor refactoring to comply with mui standards and to enable theme-aware components
- Removes uses of \<br \/\> and replaces with bottom margins
- Implements the 'sx' prop where needed
- Removes use of \<Paper\> as it created awkward aesthetics
- Removes use of \<b\> on text elements and replaces with font weight css property use
N/a.
If Yes: Has Docker been updated …
> Styling refactor

- app/client/src/Routes.jsx
- app/client/src/components/Comment.jsx
- app/client/src/components/CommentRepliesList.jsx
- app/client/src/components/CommentReply.jsx
- app/client/src/components/CreateComment.jsx
- app/client/src/components/Post.jsx
- app/client/src/redux/ducks/postDuck.js
- app/client/src/views/LoadingPage.jsx
- app/client/src/views/PostPage.jsx
- Refactored Post Page to implement the Post component, thus implementing the D.R.Y. principle
- Added comment replies
- Facelifted the CreateComment component 
> HWP-299 Added reply functionality

- app/client/src/views/AboutPage.jsx
- Updated the layout of AboutPage.jsx
- Added names and emails for us capstone students
> HWP-419 Updated About Page

- app/client/src/views/CommunityPage.jsx
- Added member count and creatorName to community page sidebar
- Added a placeholder for community rules when they are revamped.
> HWP-420: Added information to the community page sidebar

- app/client/src/components/Post.jsx
- app/client/src/layout/Header.jsx
- app/client/src/views/CommunityPage.jsx
- app/client/src/views/HomePage.jsx
- app/client/src/views/ProfilePage.jsx
- Change "Create community" button to "New +"
- Post header sizing
- Change "Your Communities" > "My Communities"
- Community page, change "Posts" > “Community Posts”
- Remove Posts link in sidebar menu
- Ellipsis on post title if title is too long
> HWP-417 UI Tweaks 

- app/client/src/App.css
- app/client/src/components/Post.jsx
- app/client/src/views/CommunitiesPage.jsx
- app/client/src/views/CommunityPage.jsx
- app/client/src/views/HomePage.jsx
- app/client/src/views/PostPage.jsx
- app/client/src/views/ProfilePage.jsx
- Reduced font-size to 85% of what it was by default.
- Re-positioned headers.
- Added ellipses to community titles on posts that are too long.
- Added padding at the bottom of all pages with content.
- Changed "Your communities" to "My communities".
- Moved plus button for adding a new community.
> Styling tweaks

- app/client/src/components/CommunitiesList.jsx
- app/client/src/components/JoinButton.jsx
- app/client/src/components/Post.jsx
- app/client/src/components/modals/DeletePostModal.jsx
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/redux/ducks/postDuck.js
- app/client/src/views/CommunityPage.jsx
- app/client/src/views/PostPage.jsx
- Joining/Leaving community is now reflected in the communityMembers field in the redux store
- Modals for deleting, flagging, and editing post are now able to be opened on PostPage.jsx
- Editing a post on CommunityPage.jsx updates the post in the redux store
- Options for editing/deleting posts that a user did not create are no longer available
- Loading CommunitiesPage.jsx now shows correct join/leave buttons
For pull requests that are not just a …
> Fixed Bugs

- app/client/src/Routes.jsx
- app/client/src/components/CreateCommunity.jsx
- app/client/src/components/GuestOnlyComponent.jsx
- app/client/src/layout/Header.jsx
- app/client/src/layout/SideMenu.jsx
- app/client/src/views/LoginPage.jsx
- Added GuestOnlyComponent.jsx
- Redirects user to the homepage if they are logged in
- Used to redirect user to the homepage if they are trying to access login or register and is logged in
- Homepage is now located at the root URL
> Homepage at root URL

- app/client/src/components/Comment.jsx
- app/client/src/components/CommentsList.jsx
- app/client/src/components/modals/FlagCommentModal.jsx
- app/client/src/redux/ducks/modalDuck.js
- app/client/src/redux/ducks/postDuck.js
- Added FlagCommentModal.jsx
- Added redux actions in modalDuck and postDuck to allow for opening the new flag comment modal, and to flag the comment.
> HWP-313 Added comment flagging functionality

- app/client/src/components/Community.jsx
- app/client/src/components/Post.jsx
- app/client/src/components/UsersCommunitiesList.jsx
- Removes borders from Post and Community card components
- Increases top margin of UserCommunitiesList component for better alignment with other page elements where it is used
Ran the application and checked for visual changes.
> HWP- : UI Spacing, Borders, and Shadows

- app/client/src/components/GuestOnlyComponent.jsx
- app/client/src/components/TagsList.jsx
- Fixed issue in TagsList.jsx which was calculating an incorrect number for number of tags a given tag has
- Removed console.logs in GuestOnlyComponent.jsx
> Incorrect Tag Badge Number Fix

- app/server/routes/v1/register.js
- app/server/tests/functions/authFunctions.js
- app/server/tests/functions/randomizer.js
- app/server/tests/userTests/api-register.test.js
This is the first part of ticket 372. Just needed to get 429 error and regex issue taken care of first. 
- Change regex in register.js to prevent infinite loop.
- Add matrix of tests to register (in prep of applying these across all tests)
- Improve authFunctions so they only call delete when needed. 
Tested on local docker build.
> HWP-372 apply matrix to register

- .github/workflows/run-tests-on-pr.yaml
> Updating Paths on CI Action

- app/client/src/Routes.jsx
- app/client/src/helperFunctions/isAPIHealthy.js
- app/client/src/views/APIDownPage.jsx
- app/client/src/views/LoadingPage.jsx
This PR adds a maintenance page which is redirected to if the API is down.
- Inclusion of the helperFunctions folder and isAPIHealthy.js
- Addition of APIDownPage.jsx
- Modified Routes.jsx to conditionally 
> HWP-375 Added maintenance page

- openshift/templates/api-dc.yaml
> HWP-451 Updating API DeployConfig Variables/Secrets

- app/server/routes/v1/post/post.js
- Added optional query param "username" to [GET API/POST](https://hwp-express-api-d63404-dev.apps.silver.devops.gov.bc.ca/api-docs/#/Post/get_api_post) to return only posts the user has created.
- This will have use in the profile page to show "Recent Posts" by user.
Swagger, create posts on 2 accounts and use GET API/POST endpoint with the new optional query.
> HWP-379: Optional username query to GET API/POST

- app/server/db.js
- app/server/dbInit/optionsCollection.js
- app/server/express.js
- docker-compose.yaml
- Fixed regex for disallowedCharacters in options collection. They weren't allowing for numbers in the string.
- Options collection will automatically refresh with new changes on server startup.
- Increased the interval for mongodb container health check in docker-compose to try to remove the mongo timeout error.
Tested creating a post with title "post123".
> HWP-441: Fixed regex for input validation

- app/client/src/components/CommunitiesList.jsx
- Removed the dependencies in the useEffect in CommunitiesList.jsx to fix an infinite loop
> Infinite Loop Fix

- openshift/templates/api-dc.yaml
HWP-458 Keycloak Feature Toggle Env Var
> HWP-458 Keycloak Feature Toggle Env Var

- app/server/versions/v1/routes/user.js
- GET /API/USER/{username} was missing fields.
> Fixed get user missing fields

- app/client/src/components/Comment.jsx
- app/client/src/components/Post.jsx
- app/client/src/views/CommunityPage.jsx
- Added link to the creator of a post in Post.jsx
- Added link to the creator of a comment in Comment.jsx
- Added link to the creator of a community in CommunityPage.jsx
> Linkage Additions

- app/client/src/components/Comment.jsx
- app/client/src/components/Tag.jsx
- app/client/src/redux/ducks/postDuck.js
- Added comment upvoting/downvoting functionality
- Modified Tag.jsx to use function based setState syntax
> HWP-296 Comment Upvoting/Downvoting

- app/client/src/components/Tag.jsx
- app/client/src/components/TagsList.jsx
- app/client/src/components/modals/AddCommunityModal.jsx
- app/client/src/components/modals/EditCommunityModal.jsx
- app/client/src/views/CommunityPage.jsx
- Updated rules and tags in create community and edit community modals.
- Updated rules on Community Page.
Tested in frontend alongside backend changes. Create community, edit community, and rules on Community page.
> HWP-462: (Frontend) Updated community rules and tags

- app/client/src/components/ProfileInfo.jsx
> Comment so that hwp-frontend builds in prod.

- docker-compose.yaml
> Fix docker-compose

- app/server/express.js
- app/server/versions/v1/routes/keycloakLogin.js
- Fixed gcNotify on KeyCloak register.
- Fixed KeyCloak api request log not displaying a log level.
Removed mongo data and registered with keycloak. Got the email.
> HWP-486: Fixed gcNotify on Keycloak register

- app/client/src/components/ProfileInfo.jsx
- app/client/src/components/modals/EditCommunityModal.jsx
- app/client/src/components/modals/EditUserBioModal.jsx
- app/client/src/components/modals/EditUserInfoModal.jsx
- app/client/src/components/modals/EditUserInterestsModal.jsx
- app/client/src/components/modals/SettingsModal.jsx
- app/client/src/redux/ducks/modalDuck.js
- app/client/src/redux/ducks/profileDuck.js
- app/client/src/theme.js
- app/client/src/views/ProfilePage.jsx
- Notification frequency can be set in the settings modal
- Interests can be set in the interests modal
- Bio modal populates text field with existing bio
> Bio, Interests, and Notification Frequency

- app/server/express.js
- app/server/versions/v1/authorization/communityAuthorization.js
- app/server/versions/v1/models/community.model.js
- app/server/versions/v1/permissions/communityPermissions.js
- app/server/versions/v1/routes/community/community.js
- app/server/versions/v1/routes/community/communityMembers.js
- app/server/versions/v1/routes/community/communityModerators.js
- app/server/versions/v1/routes/community/communityRules.js
- app/server/versions/v1/routes/community/communityTags.js
- app/server/versions/v1/routes/routeImports.js
This PR adds basic backend moderator functionality
- Added a moderators array to the community model
- Added the /api/community/moderators endpoint
- Able to GET a list of moderators for a given community
- Able to PATCH the list of moderators
- Added communityAuthorization.js which contains a helper function (isCommunityModerator) to help with authorization
- Replaced any instance of authorization if the user created the community to authorization if the user is a moderator
Please describe the tests that you …
> Backend Moderators

- app/client/src/Routes.jsx
- app/client/src/components/JoinButton.jsx
- app/client/src/components/Post.jsx
- app/client/src/components/modals/AddCommunityModal.jsx
- app/client/src/components/modals/AddPostModal.jsx
- app/client/src/components/modals/DeleteCommentModal.jsx
- app/client/src/components/modals/DeleteCommunityModal.jsx
- app/client/src/components/modals/DeletePostModal.jsx
- app/client/src/components/modals/EditCommunityModal.jsx
- app/client/src/components/modals/EditPostModal.jsx
- app/client/src/components/modals/EditUserBioModal.jsx
- app/client/src/components/modals/EditUserInfoModal.jsx
- app/client/src/components/modals/EditUserInterestsModal.jsx
- app/client/src/components/modals/FlagCommentModal.jsx
- app/client/src/components/modals/FlagPostModal.jsx
- app/client/src/components/modals/SettingsModal.jsx
- app/client/src/views/CommunityPage.jsx
- app/client/src/views/RegisterPage.jsx
This PR makes no change to functionality of the client, it removes errors that were previously building up in the console, and removes the /register route as it is no longer being used
- Reformatted code to remove errors which were flooding the console
- Removed the /register route
> Frontend Error Removal

- app/server/versions/v1/tests/api-health.test.js
- app/server/versions/v1/tests/functions/randomizer.js
- app/server/versions/v1/tests/functions/userFunctions.js
- app/server/versions/v1/tests/postTests/api-deletePost.test.js
- app/server/versions/v1/tests/postTests/api-deletePostFlags.test.js
- app/server/versions/v1/tests/postTests/api-deletePostTags.test.js
- app/server/versions/v1/tests/postTests/api-getPost.test.js
- app/server/versions/v1/tests/postTests/api-getPostFlags.test.js
- app/server/versions/v1/tests/postTests/api-getPostTags.test.js
- app/server/versions/v1/tests/postTests/api-patchPost.test.js
- app/server/versions/v1/tests/postTests/api-postPost.test.js
- app/server/versions/v1/tests/postTests/api-postPostFlags.test.js
- app/server/versions/v1/tests/postTests/api-postPostTags.test.js
- app/server/versions/v1/tests/userTests/api-deleteUser.test.js
- app/server/versions/v1/tests/userTests/api-getUser.test.js
- app/server/versions/v1/tests/userTests/api-login.test.js
- app/server/versions/v1/tests/userTests/api-patchUser.test.js
- app/server/versions/v1/tests/userTests/api-register.test.js
- Applied test matrix to remaining user/post tests. 
- Bug fixes/updates for old tests.
- Simplified randomizer to remove generated input as a barrier to test success.
- Linted old test flies.
@BradyMitch 
Some takeaways from throwing odd inputs at the endpoints...
- URLs, certain special characters, and empty strings seem to cause timeouts in most inputs. I can give you more info.
- PATCH /user seems to be expecting a notificationFrequency every time. If you don't specify it in the update, it gets upset about it being undefined. 
if your change is a breaking change, please add `breaking …
> HWP-372 apply testing matrix

- app/server/versions/v1/db/startUp.js
- app/server/versions/v1/models/user.model.js
- app/server/versions/v1/routes/comment/comment.js
- app/server/versions/v1/routes/comment/commentReply.js
- app/server/versions/v1/routes/user.js
- Changed avatar field in user schema from string type to object.
- Removed rules field from `app/server/db/startUp.js` because rules where changed from string type to object.
- Added user's avatar to comments when returned in [GET /API/COMMENT/POST/{id}](https://hwp-express-api-d63404-dev.apps.silver.devops.gov.bc.ca/api-docs/#/Comment/get_api_comment_post__id_), [GET /API/COMMENT/{id}](https://hwp-express-api-d63404-dev.apps.silver.devops.gov.bc.ca/api-docs/#/Comment/get_api_comment__id_), and [GET /API/COMMENT/REPLY/{id}](https://hwp-express-api-d63404-dev.apps.silver.devops.gov.bc.ca/api-docs/#/Comment%20Replies/get_api_comment_reply__id_)
If there are any requirements for the developer …
> HWP-125: (Backend) Profile avatar changes

- app/client/src/views/ProfilePage.jsx
- Creates variable `interestsWidth` to control the maximum width of the interests element
Changed the `maxWidth` of the 'interests' element and visually checked for changes on the profile page.
> HWP-: Interests Max Width

- app/server/versions/v1/routes/comment/comment.js
- app/server/versions/v1/routes/post/post.js
- Fixed moderators not being able to edit posts and comments
With frontend post hiding and pinning functionality.
> Fix moderator edit post and comment

- app/client/src/components/CommunitiesList.jsx
- app/client/src/components/JoinButton.jsx
- app/client/src/components/UsersCommunitiesList.jsx
- app/client/src/components/modals/AddPostModal.jsx
- app/client/src/components/modals/EditCommunityModal.jsx
- app/client/src/helperFunctions/communityHelpers.js
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/views/CommunityNotFoundPage.jsx
- app/client/src/views/CommunityPage.jsx
- app/client/src/views/ProfilePage.jsx
This PR refactors communityDuck and makes subsequent changes in Components to reflect the new format.
This change is being made to reduce duplicated data and simplify making changes to the redux store.
Instead of item being a copy of an item from the items array, item is now replaced by currentCommunityIndex which points to the specific community in the communities array.
This file adds 4 new functions and will receive more over time. Each function is used to reshape each community object into something more workable for the frontend
This file is what will be displayed when the user tries to access a community that does not exist
If there are any requirements for the developer to make after …
> Community Redux

- app/client/src/components/modals/AddCommunityModal.jsx
- app/client/src/components/modals/AddPostModal.jsx
- app/client/src/components/modals/DeleteCommentModal.jsx
- app/client/src/components/modals/DeleteCommunityModal.jsx
- app/client/src/components/modals/DeletePostModal.jsx
- app/client/src/components/modals/EditCommunityModal.jsx
- app/client/src/components/modals/EditPostModal.jsx
- app/client/src/components/modals/EditUserBioModal.jsx
- app/client/src/components/modals/EditUserInfoModal.jsx
- app/client/src/components/modals/EditUserInterestsModal.jsx
- app/client/src/components/modals/FlagCommentModal.jsx
- app/client/src/components/modals/FlagPostModal.jsx
- app/client/src/components/modals/SettingsModal.jsx
- Action buttons on modals are altered
- 'Submit' buttons are now changed to show text for the type of action being performed (i.e., Edit, Save, Delete, Post, and Flag)
- 'Cancel' buttons are now no longer of the contained variant
N/A.
> Modal Action Buttons

- app/server/versions/v1/routes/community/community.js
- Fixes issue in server's community.js where title wasn't successfully being modified
> Fixed Edit Community Title

- app/client/src/components/MarkDownEditor.jsx
- app/client/src/components/modals/AddPostModal.jsx
- Fixes bug where trying to create 2 consecutive posts in a community would result in the second post's submit button being greyed out
- Added error coloring to input labels in AddPostModal.jsx and MarkDownEditor.jsx
> Unable to Create Post Bug Fig

- app/server/versions/v1/routes/comment/comment.js
- docker-compose.yaml
- Changed mongo version from 4.0 to 3.6
- Changed **GET API/COMMENT/POST/{id}** to work with mongo version 3.6
**REMOVE the mongo image from docker desktop.**
**REMOVE all data within the** `/mongo/data` **directory.**
Comments display in frontend.
> HWP-492: Downgraded mongo version

- app/server/versions/v1/models/comment.model.js
- app/server/versions/v1/models/community.model.js
- app/server/versions/v1/models/post.model.js
- app/server/versions/v1/routes/comment/commentFlags.js
- app/server/versions/v1/routes/community/communityFlags.js
- app/server/versions/v1/routes/post/postFlags.js
- Changes the flaggedBy field in the flags array to store usernames instead of user ids
> Modified flaggedby array to use username

- app/client/src/components/modals/EditUserBioModal.jsx
- app/client/src/redux/ducks/modalDuck.js
- app/client/src/views/ProfilePage.jsx
- Fixes issue where Bio would not populate the text field in EditUserBioModal.jsx
> Bio Shows Up In EditUserBioModal.jsx

- app/server/versions/v1/routes/community/communityMembers.js
- If the user is the last member of a community when trying to leave it, they can leave it and the community will be removed.
- Before, it would give an error saying you need to remove permissions before leaving.
> Fixed leave community

- app/server/db.js
- app/server/versions/v1/jobs/communityUnKick.js
- app/server/versions/v1/models/community.model.js
- app/server/versions/v1/routes/community/communityMembers.js
- app/server/versions/v1/routes/community/communityModerators.js
- Added kicked to community schema
```
kicked: [
{
userId: String,
period: String,
periodEnd: String,
},
],
``` 
- Added **POST API/COMMUNITY/MODERATORS/KICK/{title}** to kick users from the community. Use `test` value for `period` field to kick for 5 minutes. Valid values are `test` `hour` `day` `week` and `forever`
- Changed response body for **GET API/COMMUNITY/MEMBERS/{title}** to show more user data.
Tested in swagger. Kicked user and removed from kicked array after 5 minutes.
For pull requests that are …
> HWP-491: Kick community members

- app/server/versions/v1/routes/comment/comment.js
- app/server/versions/v1/routes/comment/commentFlags.js
- app/server/versions/v1/routes/comment/commentReply.js
- app/server/versions/v1/routes/community/communityFlags.js
- app/server/versions/v1/routes/post/postFlags.js
- Added DELETE API/POST/FLAGS/RESOLVE/{id} To resolve all flags on a post.
- Added DELETE API/COMMENT/FLAGS/RESOLVE/{id} To resolve all flags on a comment.
- Optional query param "show=true" will un-hide post or comment.
Tested new endpoints in swagger.
> HWP-478: (Backend) Flag resolving on posts and comments

- app/client/src/components/Community.jsx
- app/client/src/components/InputRuleList.jsx
- app/client/src/components/MarkDownDisplay.jsx
- app/client/src/components/MarkDownEditor.jsx
- app/client/src/components/Post.jsx
- app/client/src/components/RuleInput.jsx
- app/client/src/components/modals/AddCommunityModal.jsx
- app/client/src/components/modals/EditCommunityModal.jsx
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/views/CommunityPage.jsx
- Changed the way Community rules are input in both EditCommunityModal and AddCommunutyModal
- Added Markdown capabilities to community description
- Created a MarkDownDisplay component to render markdown 
- Added InputRuleList.jsx and RuleInput.jsx to change how rule creation works
- Changed communityDuck's editCommunity function to take in a community name and a changes object seperately
For pull requests that are not just a simple fix, please …
> Zach community description

- app/client/src/components/modals/DemoteUserModal.jsx
- app/client/src/components/modals/PromoteUserModal.jsx
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/redux/ducks/modalDuck.js
- app/client/src/views/CommunityPage.jsx
This PR adds functionality to promote and demote users to be moderators of a community
- Addition of PromoteUserModal.jsx and DemoteUserModal.jsx
- Redux actions to promote and demote users
> HWP-466 / HWP-468 | Promote and Demote Users

- app/client/package-lock.json
- app/client/package.json
- app/client/src/components/Post.jsx
- app/client/src/components/modals/EditCommunityModal.jsx
- app/client/src/components/modals/ResolveFlagsModal.jsx
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/redux/ducks/modalDuck.js
- app/client/src/redux/ducks/moderatorDuck.js
- app/client/src/redux/ducks/postDuck.js
- app/client/src/redux/index.js
- app/client/src/views/CommunityPage.jsx
- app/client/src/views/HomePage.jsx
- app/client/src/views/PostPage.jsx
- Added ResolveFlagsModal.jsx to allow admin users to resolve flags for a given post
- Added moderatorDuck.js to house moderator actions
- Added the MUI DataGrid through npm
> HWP-478 Resolve Flags

- app/client/src/components/Post.jsx
- app/client/src/components/modals/PromoteUserModal.jsx
> Minor tweaks

- app/server/versions/v1/db/startUp.js
- Added removed and hidden fields to existing posts in db/startUp.js
Created a post without removed and hidden fields in mongo CLI and then restarted the server.
> Fixed existing posts not visible

- app/client/src/components/modals/EditPostModal.jsx
- Fixed not being able to edit posts
> Fixed post edit

- app/client/src/components/Post.jsx
- Added styling to removed posts (only Admins can see removed posts).
Post styling displays in frontend.
> HWP-493: Added styling to removed posts

- app/server/express.js
- app/server/swagger/tags.js
- app/server/versions/v1/routes/routeImports.js
- app/server/versions/v1/routes/search.js
- Added **GET /api/search/{query}**
- Search query is case insensitive
- Returns `{ users: [], communities: [], posts: [] }`
- If no results match your search, returns **"No results found."**
- Search users by username, firstName, lastName, or fullName.
- Search communities by title.
- Search posts by title and message.
- Advanced search query `author:<username>` or `creator:<username>` returns posts created by <username>. Use like: `author:jeff test`
- Advanced search query `latestActivity: ` returns communities in order of latestActivity. Use like `latestActivity: test`
if your change is a …
> HWP-469: Backend Search

- app/server/versions/v1/routes/user.js
- Addition of community description to the community object returned from the user endpoint
> Add Community Description to User Response

- app/server/versions/v1/classes/logger.js
- app/server/versions/v1/db/startUp.js
- app/server/versions/v1/functions/auth/communityAuthorization.js
- app/server/versions/v1/functions/auth/generateToken.js
- app/server/versions/v1/functions/checkUserIsMemberOfCommunity.js
- app/server/versions/v1/functions/findCommunitiesByEngagement.js
- app/server/versions/v1/functions/findSingleDocuments.js
- app/server/versions/v1/models/user.model.js
- app/server/versions/v1/routes/comment/comment.js
- app/server/versions/v1/routes/comment/commentFlags.js
- app/server/versions/v1/routes/comment/commentReply.js
- app/server/versions/v1/routes/comment/commentVoting.js
- app/server/versions/v1/routes/community/community.js
- app/server/versions/v1/routes/community/communityFlags.js
- app/server/versions/v1/routes/community/communityMembers.js
- app/server/versions/v1/routes/community/communityModerators.js
- app/server/versions/v1/routes/community/communityRules.js
- app/server/versions/v1/routes/community/communityTags.js
- app/server/versions/v1/routes/keycloakLogin.js
- app/server/versions/v1/routes/login.js
- app/server/versions/v1/routes/logout.js
- app/server/versions/v1/routes/post/post.js
- app/server/versions/v1/routes/post/postFlags.js
- app/server/versions/v1/routes/post/postTags.js
- app/server/versions/v1/routes/register.js
- app/server/versions/v1/routes/token.js
- app/server/versions/v1/routes/user.js
- Added `role` field to User schema.
- Changed function checkUserIsMemberOfCommunity to take in user instead of user.username.
- Admin can edit documents without any disallowed fields.
- Admin can edit and delete any document.
- Admin can remove or permanently delete any document.
- Admin can delete other users.
- Added patch query to Logger class to mask and display the patch query on some requests.
- Admin can see `removed` documents.
- Fixed comment replies not showing up and comment reply votes.
**How to test:**
In mongo CLI, give `george` admin role with `db.user.updateOne({ "username": "george" }, { $set: { "role": "admin" } })`
Log out as `george` and log back in.
If there are any …
> HWP-515: Added admin user

- app/client/docker/dev/Dockerfile
- app/client/docker/prod/Dockerfile
- app/client/src/components/modals/CommunityMembersModal.jsx
- app/client/src/components/modals/KickUserModal.jsx
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/redux/ducks/modalDuck.js
- Moderators can kick (suspend) members from the communities that they moderate through use of a modal UI in the frontend application
- Adds an ENV field to the client dockerfiles which stops puppeteer from downloading chromium, this fixes a compatibility issue with Apple Silicon devices
Using swagger, log in as a user and join a community that is moderated by your IDIR account. As your IDIR user suspend the swagger user from the community. Afterwards, try to rejoin the community within the suspension period. …
> Frontend moderator kick user

- .github/dependabot.yaml
-  the dependencies are not being updated in the server and client, thought they should be. 
> HWP-341 Investigate Prototype Pollution in async Dependabot Vulnerability

- .github/workflows/run-codeql-scan.yaml
- Added workflow that should run CodeQL scan and add found vulnerabilities to the Security tab
Only set this to run when manually triggers or if this workflow is edited in a pull request. Don't want it running too often for now.
Tested against other repos. Generates desired results.
> HWP-494 Added workflow for CodeQL scan

- app/client/src/components/Comment.jsx
- app/client/src/components/CommentRepliesList.jsx
- app/client/src/components/CommentReply.jsx
- app/client/src/components/CommentsList.jsx
- app/client/src/components/CreateComment.jsx
- app/client/src/components/modals/DeleteCommentModal.jsx
- app/client/src/components/modals/EditUserInterestsModal.jsx
- app/client/src/components/modals/FlagCommentModal.jsx
- app/client/src/helperFunctions/commentHelpers.js
- app/client/src/helperFunctions/communityHelpers.js
- app/client/src/helperFunctions/postHelpers.js
- app/client/src/redux/ducks/commentDuck.js
- app/client/src/redux/ducks/postDuck.js
- app/client/src/redux/index.js
- app/client/src/views/CommunityPage.jsx
- app/client/src/views/PostPage.jsx
- app/client/src/views/ProfilePage.jsx
This PR makes changes to the way that the postDuck is structured. Making said changes result in optimized data storage and improved website speed due to less comparisons.
postDuck.js now aligns with communityDuck.js by using a currentPostIndex and an array of posts to dictate
- Refactored postDuck.js
- Added commentDuck.js
- communityDuck does not have any data in its reducer due to comments being kept on  the post object itself
- Changed the way comment voting is handled
- Removed console.logs from frontend
- added commentHelper.js and postHelper.js to add useful data to each object respectively
If there are any requirements for the developer to make after this PR is merged please list them …
> Post Redux Refactor

- app/client/src/components/Community.jsx
- app/client/src/components/ProfileInfo.jsx
- app/client/src/redux/ducks/profileDuck.js
- app/client/src/theme.js
- app/client/src/views/ProfilePage.jsx
- Added mailto link to profile
- Conditionally rendering users posts and communities
- Fixed bug where incorrect profile was displaying
- Updated profile page ui
> HWP-504 && HWP-507 | Profile Page

- app/server/versions/v1/db/init/optionsCollection.js
- app/server/versions/v1/db/startUp.js
- app/server/versions/v1/functions/validateCommunityInputs.js
- app/server/versions/v1/models/community.model.js
- app/server/versions/v1/routes/community/community.js
- Added community resources to Community schema
Swagger
> HWP-508: Added community resources

- app/server/versions/v1/routes/comment/comment.js
- Comment replies would decrement the comment count and wouldn't set hasReplies to false on the replyTo comment when the reply was deleted.
> HWP-523: Fixed comment replies count

- app/server/versions/v1/routes/search.js
- Search no longer shows removed posts.
> HWP-522: Fixed search showing removed posts

- app/client/src/components/JoinButton.jsx
- app/client/src/components/RuleInput.jsx
- app/client/src/views/CommunityPage.jsx
- Added community resources to Community page (Currently no way to set this outside of swagger. This will come in later changes.)
- Moved around components of the Community Page.
Viewed in frontend.
> HWP-511: Community resources widget & Community page tweaks

- app/client/src/components/Croutons.jsx
- app/client/src/views/CommunityPage.jsx
- app/client/src/views/HomePage.jsx
- app/client/src/views/PostPage.jsx
- Creates custom breadcrumb component called Croutons.jsx
- Implements Croutons across application
> HWP-283: Breadcrumbs

- app/server/versions/v1/routes/search.js
- Removed 404 case from backend search
> Removed 404 Case From Search

- app/client/src/Routes.jsx
- app/client/src/components/Post.jsx
- app/client/src/layout/Header.jsx
- app/client/src/redux/ducks/searchDuck.js
- app/client/src/redux/index.js
- app/client/src/views/SearchPage.jsx
- Search bar now grows and shrinks depending on focus
- Added SearchPage.jsx
- Added searchDuck.js
This PR requires the backend changes specified in #431 
> HWP-471 Frontend Search

- app/client/src/components/JoinButton.jsx
- app/client/src/components/Post.jsx
- app/client/src/components/UsersCommunitiesList.jsx
- app/client/src/views/CommunitiesPage.jsx
- app/client/src/views/HomePage.jsx
- Added tooltips to community members icon, comments icon, leave community icon, and plus buttons.
> HWP-529: Added more tooltips

- app/client/src/components/InputRuleList.jsx
- app/client/src/components/RuleInput.jsx
- app/client/src/components/modals/AddCommunityModal.jsx
- app/client/src/components/modals/CommunityMembersModal.jsx
- app/client/src/components/modals/EditCommunityModal.jsx
- app/client/src/redux/ducks/communityDuck.js
- Ability to add/edit community resources in the add community or edit community modals
- Changed add community and edit community modal to use pages instead of scrolling down.
Tested in frontend adding and editing communities.
> HWP-511: Add/Edit Community Resources + Modal Changes

- app/client/src/components/ModListItem.jsx
- app/client/src/components/modals/KickUserModal.jsx
- app/client/src/views/CommunityPage.jsx
- Fixed bug where editing permissions or demoting a user would focus on the last user in the list
- Removed console.log from KickUserModal.jsx
> HWP-509 Moderator Permissions Bug

- app/client/src/views/AboutPage.jsx
> HWP-530: Tweaks to about page

- app/server/versions/v1/functions/validateCommunityInputs.js
- Renamed "contains" function to includes in validateCommunityInputs.js
> Create Community With Tags Fix

- app/client/src/components/Post.jsx
- app/client/src/components/PostsList.jsx
- app/client/src/components/UsersCommunitiesList.jsx
- app/client/src/components/modals/AddPostModal.jsx
- app/client/src/components/modals/EditPostModal.jsx
- app/client/src/components/modals/ResolveFlagsModal.jsx
- app/client/src/redux/ducks/postDuck.js
- app/client/src/views/CommunityPage.jsx
- Post title is no longer truncated on singular post page
- Flagged/Pinned icons on Post only gets displayed on community page
- Fixed issue where clicking on a tooltip would redirect to the incorrect location
- Updated min/max post title character limits in AddPostModal and EditPostModal
- Removed unneeded createError/createSuccess's when tagging/untagging posts
For pull requests that are not just a simple fix, please check that the branch works …
> HWP-501 Fixed Post Related Issues

- app/client/src/components/modals/CommunityMembersModal.jsx
- app/client/src/theme.js
- Members in members list show online status with tooltip on hover.
> Added online status to members list

- app/client/src/components/Comment.jsx
- app/client/src/components/CommentRepliesList.jsx
- app/client/src/views/CommunityPage.jsx
- Added tooltips to comment voting.
> Added voting tooltips

- app/client/src/components/modals/AddCommunityModal.jsx
- app/client/src/components/modals/EditCommunityModal.jsx
- Fixed the height of community add and edit modals.
> Fixed community modal

- app/client/src/components/Post.jsx
- app/client/src/components/modals/AddCommunityModal.jsx
- app/client/src/views/CommunitiesPage.jsx
- app/client/src/views/CommunityPage.jsx
- app/client/src/views/HomePage.jsx
- Fixed over-fetching of community info in Post.jsx
- AddCommunityModal now redirects to the community you create
- Added background color to HomePage posts list
> Fixed Overfetching in Frontend

- app/client/src/components/modals/CommunityMembersModal.jsx
- app/client/src/views/ProfilePage.jsx
- Basic implementation of online status.
- Shows in community members modal and profile page.
- KNOWN ISSUE: Your own online status will always display as online when viewing your own profile.
> HWP-443: Added online status to profile page

- app/client/src/components/Community.jsx
- app/client/src/components/Croutons.jsx
- app/client/src/views/AboutPage.jsx
- app/client/src/views/CommunitiesPage.jsx
- app/client/src/views/ProfilePage.jsx
- app/client/src/views/SearchPage.jsx
- Rectifies missing 'Crouton' implementations
Ran the application in a dev environment and visually checked each page for breadcrumbs at the top of the page.
> Croutons fix

- app/client/src/Routes.jsx
- app/client/src/components/AdminStatusBox.jsx
- app/client/src/components/modals/AdminDeleteUserModal.jsx
- app/client/src/components/modals/AdminEditUserModal.jsx
- app/client/src/components/modals/AdminGetUserModal.jsx
- app/client/src/layout/Header.jsx
- app/client/src/redux/ducks/adminDuck.js
- app/client/src/redux/ducks/modalDuck.js
- app/client/src/redux/index.js
- app/client/src/views/AdminPage.jsx
REQUIRES backend changes pr.
- Only available to user's with role === "admin"
- Open admin dashboard from navigation menu.
- Displays status boxes to show flagged communities, posts, and comments.
- Displays data grids to show all user, community, post, and comment information.
- Ability to get raw user data.
- Ability to edit user data.
- Ability to delete a user.
REQUIRES backend changes pr.
Tested alongside backend changes for HWP-470. Status is displayed, get, edit, and delete operations on user all …
> HWP-470: Admin page

- app/client/src/components/Comment.jsx
- app/client/src/components/CommentRepliesList.jsx
- app/client/src/components/modals/DeleteCommentModal.jsx
- app/client/src/redux/ducks/commentDuck.js
- app/client/src/redux/ducks/modalDuck.js
- app/client/src/redux/ducks/postDuck.js
- Changed the way comment voting works
- Comment reply voting now updates in the frontend
- Comment reply editing now updates in the frontend
- Comment reply deleting now updates in the frontend
> HWP-502 Comment fixes

- app/server/versions/v1/db/startUp.js
- Drops all data from database except users and welcome community.
> Drops data from database

- app/server/versions/v1/db/startUp.js
- app/server/versions/v1/routes/user.js
- Fixed an issue where you couldn't edit profile
> Adds admin users and fixes edit profile

- app/client/src/components/Community.jsx
- app/client/src/components/UsersCommunitiesList.jsx
- app/client/src/views/CommunityPage.jsx
- Added background to UsersCommunitiesList
- Fixed bug
> Visual Bug Fix

- app/server/versions/v1/routes/user.js
> Fixed edit profile
