bcgov/CITZ-HybridWorkplace

- app/client/env.sh
- env-config was creating variables for empty lines or comments when reading the env-template
Tested cat on env-config.js in frontend
> Fixed env-config.js creating variables for empty lines in env-template

- app/client/Dockerfile
- app/client/README.md
- app/client/env.sh
- app/client/src/actions/communityActions.js
- app/client/src/components/communitiesList.js
- app/client/src/components/createCommunity.js
- app/client/src/components/joinCommunitiesList.js
- app/client/src/components/modals/addPost.js
- app/client/src/components/newCommunity.js
- app/client/src/views/communitiesPage.js
- docker-compose.yaml
- init-mongodb/data/communities.json
- added communitiesList component 
- Dockerfile for client has a comment to differentiate production vs. development config for env variables. This will need to have a better solution but for now this allowed it to work in dev.
- change to env.sh to allow proper import of env variables in developement.
Ran docker-compose, checked env variables in frontend cli with cat env-config.js
Communities list does show up when rate limiting is commented out, this is a known issue that should be fixed when redux code is changed
Small non breaking changes to docker-compose and client Dockerfile
> Hwp-211: communitieslist, frontend env-variables working in development

- docker-compose.yaml
The old mongo image, mongo:4.2.20, was not working with the health check added to the docker-compose.yaml. It would often give the error: container is unhealthy.
**REQUIRES**:
For change to take effect:
1. Run `docker-compose down -v` to remove all running containers
2. In Docker Desktop, delete the mongo image, and all volumes
3. Rebuild the project with `docker-compose up --build`
POSSIBLY REQUIRED:
Re-clone of the project
- Changed docker-compose.yaml to use mongo:4 instead of mongo:4.2.20
Please describe the tests that you ran to verify your …
> Changed mongo image to mongo:4

- app/client/src/redux/ducks/authDuck.js
Reverting previous test. Thought maybe process.env would possibly pull the correct env variable for api reference.
The window._env_ for REACT_APP_API_REF is not being set to the correct api ref for openshift.
> Reverting previous test for process.env

- app/client/src/components/modals/addPost.js
- app/client/src/redux/ducks/authDuck.js
- app/client/src/redux/ducks/postDuck.js
- Changed addPost modal to send the community name in place of the community ID to align with the API changes in HWP-302
> Sending community name in community field instead of community id

- app/client/src/layout/sideMenu.js
- app/client/src/redux/ducks/authDuck.js
- Added logout to authDuck.js
- Modified sideMenu.js to call logout action
- Added credentials: "include" to login and logout redux actions
This PR stores the refresh token as an httpOnly cookie, currently said cookie is not being used to create a new access token. That will be done when the custom axios instance is implemented.
If Yes: Has …
> HWP-307 Frontend Refresh Token storage

- .env-template
- app/server/express.js
- app/server/routes/v1/login.js
- app/server/routes/v1/logout.js
- app/server/routes/v1/token.js
**DO NOT MERGE** until frontend changes have been made. These changes are SERVER-SIDE. In testing, I edited part of the client-side code to verify the cookie was being set, but have not saved those changes to this pull request.
- Updated cors options in app/server/express.js
- Hashed refreshToken before storing in database.
- Added 'secure' and 'sameSite' options to refresh token cookie.
- Updated env-template.
- app/server/express.js: cors origin field is set for local dev, and hard-coded for openshift DEV. Its set up so it should mean we just need to add the env variables into the openshift config. I have added a ticket to backlog for this to be done (HWP-328). @akroon3r 
@ZachBourque Here's what needs to happen on the frontend:
- …
> HWP-327: Fixed JWT cookie not being set in frontend

- app/client/src/components/modals/addPostModal.js
- Changed postModal.js to use the usersCommunities array from the redux store as opposed to the all communities array
> Post Modal only lists community the user is a part of

- .env-template
- app/server/models/user.model.js
- app/server/routes/v1/comment/comment.js
- app/server/routes/v1/comment/commentReply.js
- app/server/routes/v1/community/community.js
- app/server/routes/v1/community/communityMembers.js
- app/server/routes/v1/post/post.js
- app/server/routes/v1/register.js
- docker-compose.yaml
- When using GET /api/community, you can specify the optional query parameter "orderBy" equal to "engagement" and communities that are returned will be ordered by your engagement in the community.
- Engagement ratings can be increased by creating the community, creating a post, or creating a comment.
- Engagement ratings can decrease by removing posts, or comments.
- The weight of each action is currently: create_community=0, create_post=5, create_comment=1
- We can use this engagement rating anywhere we want in the community. We can make voting have an engagement value, etc.
@ZachBourque in …
> HWP-306: Order communities by engagement option

- app/client/src/components/Comment.jsx
- app/client/src/components/CommentsList.jsx
- app/client/src/components/modals/DeleteCommentModal.jsx
- app/client/src/redux/ducks/modalDuck.js
- app/client/src/redux/ducks/postDuck.js
This PR provides functionality in the frontend for the user to delete their own comment.
- Addition of DeleteCommentModal.jsx
- Created deleteComment redux action
- Added ellipses on the top right corner of the Comment component to allow the user to delete their comment
> Added comment deletion functionality

- app/client/src/components/PostsList.jsx
- app/client/src/views/CommunityPage.jsx
- app/client/src/views/HomePage.jsx
- app/client/src/views/PostsPage.jsx
This PR fixes an issue in CommunitiesPage.jsx where said page was displaying all posts, not just posts specific to that community.
- Modified PostsList.jsx to take in a posts array as props
- Modified all instances of PostsList to pass in a posts array as props
> HWP-405 Community page only display posts in that community

- app/server/routes/v1/comment/comment.js
Because of the logger, I was able to find this bug in seconds. The checkPatchQuery function was being called with a parameter of documents.community when it should have been documents.comment
> HWP-407: Bug fixed in comment.js route checkPatchQuery() parameters

- app/client/src/views/ProfilePage.jsx
- Adjusts padding of 'Your Communities' tiles
- Replaces use of 'style' with 'sx' on the profile page
- Removes \<br \/\> elements and uses margin to space elements on profile page
No tests needed. Visual changes and minor refactoring only.
> Adjusts community tile sizing

- app/client/src/components/Comment.jsx
- Comment edit was showing the wrong date.
- Converted `substr` to `substring`, as `substr` is depricated and may have its support dropped at some point in the future.
Tested in frontend after making an edit to a comment.
> HWP-415: Fixed comment edit showing wrong date

- app/server/routes/v1/comment/commentReply.js
- creatorName wasn't being set on comment replies.
Replied to a comment on frontend application.
> HWP-422: Fixed creatorName not being set on comment reply

- app/client/src/App.jsx
- app/client/src/views/CommunitiesPage.jsx
- app/client/src/views/HomePage.jsx
Makes some minor style changes to the homepage and communities page right-side banner vertical padding and adds custom styling to mui LoadingButton components that are using the 'disabled' property.
- Increases padding of communities page right-side header banner so that it matches the homepage
- Centres the text of the right-side header banner on the homepage
- Adds a custom css rule for disabled mui LoadingButton components
Added the new rule and then added an MuiLoadingButton to a page and tried with and …
> HWP- : LoadingButton Component Override

- app/server/routes/v1/post/postTags.js
- When a second user tried to tag a post that was previously tagged, it would not set the tag.
Used swagger to tag a post with one account, and then tagged the same post on a second account.
> HWP-427: Fixed post tagging

- app/server/routes/v1/community/community.js
- docker-compose.yaml
- Added value "latestActivity" to "orderBy" optional query param on [GET API/COMMUNITY](https://hwp-express-api-d63404-dev.apps.silver.devops.gov.bc.ca/api-docs/#/Community/get_api_community). Returns only communities user is a member of and orders by latestActivity.
Swagger. Tested the new "latestActivity" value in "orderBy" on GET API/COMMUNITY.
**It seems part of docker-compose was commented out in a …
> HWP-382: Order communities by latestActivity

- app/client/src/App.jsx
- app/client/src/components/modals/SettingsModal.jsx
- app/client/src/theme.js
- Changes Darkmode switch in SettingsModal.jsx to a Select (Dropdown)
- On saving, the page reloads to reflect the users dark mode preference
- Moved theme from App.jsx to theme.js
> Added Darkmode to Settings

- app/client/src/components/CommentReply.jsx
- app/client/src/layout/Header.jsx
- Fixed Header.jsx's menu to not have a color overlay
- Fixed buttons in CommentReply.jsx to not have text be the color of the button itself
> Fixed Darkmode Bugs

- app/server/versions/v1/routes/community/community.js
Previously, when editing a community, if you did not specify a title in the changes object, the title would be set as undefined in the database.
- Added check in community.js if the community name doesn't exist, if so it adds the community name from params
> Undefined Community Name Fix

- app/client/src/views/CommunityPage.jsx
- Removed "Created by:" label
- Added "Moderated by:" list
Moderator view for the list works if `isModerator = true`. This still needs to be retrieved from `props.community`, the modals still need to be made for moderator settings. This is just the visual aspect of the implementation for moderator list.
Tested setting isModerator to true and false and viewing in frontend.
If Yes: Has Docker been updated …
> HWP-304: Added moderators list to community page

- app/client/src/components/Comment.jsx
- app/client/src/components/Post.jsx
- app/client/src/components/modals/EditPostModal.jsx
- app/client/src/redux/ducks/postDuck.js
- Still requires the code to be implemented that tells if the user is a moderator or not. **To test**, look for variable `isModerator`.
- Styles the post header to gray and adds a "Not Visible" icon to posts that are hidden (hidden posts are only visible to community moderators).
- Adds a "pinned" icon to post headers that are pinned.
- Adds menu options on posts for pinning/un-pinning and hiding/showing the post (only available to community moderators).
- **Requires:** https://github.com/bcgov/CITZ-HybridWorkplace/pull/362 To allow editing of posts that are not created by you.
if your …
> HWP-475: Hidden and pinned posts

- app/client/src/components/modals/EditModPermsModal.jsx
- app/client/src/redux/ducks/communityDuck.js
- app/client/src/redux/ducks/modalDuck.js
- app/client/src/views/CommunityPage.jsx
- Added a modal for moderators to edit permissions of other moderators
- Only displays option to set permissions if the moderator has `set_permissions` permission
Created a test community and edited my own permissions.
> HWP-304: Moderator permissions modal

- app/server/versions/v1/functions/findCommunitiesByEngagement.js
- app/server/versions/v1/routes/user.js
- Add createdOn, latestActivity, and members fields to communities when returned by GET api/user for better use in the frontend.
- Fix for get communities by engagement, wasn't grabbing engagement data from correct user.
Swagger.
> HWP-520: Changes to returned user communities in api/user

- app/client/src/components/Community.jsx
- app/client/src/components/Post.jsx
- app/client/src/components/UsersCommunitiesList.jsx
- app/client/src/components/modals/AddCommunityModal.jsx
- app/client/src/components/modals/AddPostModal.jsx
- app/client/src/components/modals/EditCommunityModal.jsx
- app/client/src/components/modals/EditPostModal.jsx
- app/client/src/views/CommunityPage.jsx
- app/server/versions/v1/db/init/optionsCollection.js
- Community card shows icon and number to display how many posts are in the community.
- Community title max length increased to 200.
- Made changes to allow setting of 200 character post titles in frontend.
- Moved "Created on" label for communities to the subheader.
Visible in frontend. Tested max community and title lengths.
> HWP-512: Community UI tweaks, title length, and postCount

- app/server/express.js
- app/server/versions/v1/db/startUp.js
- app/server/versions/v1/jobs/defineOfflineStatusJob.js
- app/server/versions/v1/jobs/startUp.js
- app/server/versions/v1/middleware/setOnlineStatus.js
- app/server/versions/v1/models/user.model.js
- app/server/versions/v1/routes/community/communityMembers.js
- app/server/versions/v1/routes/community/communityModerators.js
- app/server/versions/v1/routes/keycloakLogin.js
- app/server/versions/v1/routes/login.js
- app/server/versions/v1/routes/logout.js
- app/server/versions/v1/routes/onlineStatus.js
- app/server/versions/v1/routes/routeImports.js
- app/server/versions/v1/routes/search.js
- app/server/versions/v1/routes/user.js
- Added `online status` (boolean) to User schema.
- Login and almost all endpoints set the user's online status for **5 minutes**.
- After the 5 minutes if the user hasn't been active they become offline.
- Added online status to **GET /api/user/{username}** to tell if other users are online.
- Added **GET /api/online** to tell if you (current user) is online.
- Online status is set to false on server startup.
- Unkick jobs wouldn't reschedule after server shutdown and startup if they had passed their scheduled run time, so I added a function to compare the current date to the periodEnd date to see if users should be unkicked right away or reschedule for however many hours they had left to wait.
Add 'Requires Attention' label if …
> HWP-517: Added online status
